<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class QuizController extends Controller
{
    public function saveResult(Request $request) {
    \App\Models\QuizResult::updateOrCreate(
        [
            'user_id' => auth()->id(),
            'lecture_file_id' => $request->file_id
        ],
        [
            'score' => $request->score,
            'correct_answers' => $request->correct,
            'total_questions' => $request->total
        ]
    );

    return response()->json(['success' => true]);
}
// دالة تصدير تقرير الكويز باللغة الإنكليزية
public function downloadEnglishReport($fileId) 
{
    // 1. جلب بيانات النتيجة من الداتابيز
    // ملاحظة: تأكدي أن اسم الموديل عندك QuizResult أو حسب ما سميتيه
    $quizResult = \App\Models\QuizResult::where('lecture_file_id', $fileId)
                            ->where('user_id', auth()->id())
                            ->latest()
                            ->firstOrFail();

    // 2. تجهيز محتوى التقرير (نصي حالياً للسرعة)
    $content = "------------------------------------------\n";
    $content .= "       UNISMART ACADEMIC REPORT          \n";
    $content .= "------------------------------------------\n\n";
    $content .= "Student Name: " . auth()->user()->name . "\n";
    $content .= "Lecture Reference ID: " . $fileId . "\n";
    $content .= "Status: Completed\n";
    $content .= "------------------------------------------\n";
    $content .= "Final Grade: " . $quizResult->score . "%\n";
    $content .= "Correct Answers: " . $quizResult->correct . " out of " . $quizResult->total . "\n";
    $content .= "------------------------------------------\n";
    $content .= "Generated by Veloria AI on: " . now()->format('Y-m-d H:i') . "\n";

    // 3. إرسال الملف للمتصفح للتحميل
    return response($content)
            ->withHeaders([
                'Content-Type' => 'text/plain',
                'Content-Disposition' => 'attachment; filename="UniSmart_Quiz_Report.txt"',
            ]);
}

}
